#!/bin/bash
# This hook is run after every virtualenv is activated.

#If the user has any personal preferences they should be set 
#per environment in this file
if [ -f $VIRTUAL_ENV/prefs ]; then
        . $VIRTUAL_ENV/prefs
fi

cd $VIRTUAL_ENV/src
