#!/bin/bash
# This hook is run after every virtualenv is activated.

#If the user has any personal preferences they should be set 
#per environment in this file
if [ -f $VIRTUAL_ENV/envrc ]; then
        . $VIRTUAL_ENV/envrc
fi

cd $VIRTUAL_ENV/src
